### ISSUE TITLE
Tests failing due to no GH_TOKEN

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/coherent.build#21]
The tests for this project are currently failing in CI due to:

```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}
```

**Comment by jaraco** [comment]
@bswck Do you think this environment variable can and should be set at the system workflow? I'm thinking it sort-of has to be, because these workflows are going to be building and releasing the project, so to generate the proper metadata, they'll need to query github.

**Comment by johnslavik** [comment]
I'm thinking a global approach (`env: GH_TOKEN: ${{ github.token }}` set globally) is OK for our current use cases (`permissions: contents: read`).

However, in `permissions: write` scenarios, I'm thinking that the `GH_TOKEN` environment variable could ideally be set from the reusable workflow in a fine-grained manner (only in the steps that necessitate it), controlled by workflow inputs. This way every job that really needs the GitHub token will receive a separate, temporary token to work with.

**Comment by johnslavik** [comment]
Refs:
- https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions

**Comment by johnslavik** [comment]
I guess what we can do now is set `env: GH_TOKEN: ${{ github.token }}` in the `tests` job definition (maybe only in the last step that runs tests) with read permissions only. That should fix this issue.

**Comment by johnslavik** [comment]
In coherent-oss/system@56c821a, I've shared the token via `GH_TOKEN` with the final step of the `tests` job, and [the tests pass](https://github.com/coherent-oss/coherent.build/actions/runs/10410486952) since.
